[build]
publish = "dist"
command = "npm ci && npm run lint && npm run build -- --configuration production"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
